services:
  nginx:
    build: .
    ports:
      - "${NGINX_PORT:-8080}:${NGINX_PORT:-8080}"
    container_name: nginx_hello
    environment:
      - NGINX_PORT=${NGINX_PORT:-8080}
      - NGINX_WORKER_CONNECTIONS=${NGINX_WORKER_CONNECTIONS:-1024}
      - ENVIRONMENT=${ENVIRONMENT:-local}
    env_file:
      - .env