apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  labels:
    app: nginx-hello
    environment: local
data:
  NGINX_PORT: "8080"
  NGINX_SERVER_NAME: "${DOMAIN_1} ${DOMAIN_2} ${DOMAIN_3}"
  NGINX_WORKER_CONNECTIONS: "1024"