apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-hello-config
  labels:
    app: nginx-hello
data:
  NGINX_PORT: {{ .Values.config.nginxPort | quote }}
  NGINX_SERVER_NAME: {{ join " " .Values.config.domains | quote }}
  NGINX_WORKER_CONNECTIONS: {{ .Values.config.nginxWorkerConnections | quote }}