{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "nginx-hello.fullname" . }}-ingress
  labels:
    {{- include "nginx-hello.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  {{- if .Values.ingress.tls }}
  tls:
    {{- range .Values.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- else if and .Values.tls .Values.tls.enabled }}
  tls:
    - hosts:
        {{- if .Values.domain1 }}
        - {{ .Values.domain1 | quote }}
        {{- end }}
        {{- if .Values.domain2 }}
        - {{ .Values.domain2 | quote }}
        {{- end }}
        {{- if .Values.domain3 }}
        - {{ .Values.domain3 | quote }}
        {{- end }}
      secretName: {{ .Values.tls.secretName }}
  {{- end }}
  rules:
    {{- if .Values.ingress.hosts }}
    {{- range .Values.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ include "nginx-hello.fullname" $ }}-service
                port:
                  number: {{ $.Values.service.port }}
          {{- end }}
    {{- end }}
    {{- else }}
    {{- if .Values.domain1 }}
    - host: {{ .Values.domain1 | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "nginx-hello.fullname" . }}-service
                port:
                  number: {{ .Values.service.port }}
    {{- end }}
    {{- if .Values.domain2 }}
    - host: {{ .Values.domain2 | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "nginx-hello.fullname" . }}-service
                port:
                  number: {{ .Values.service.port }}
    {{- end }}
    {{- if .Values.domain3 }}
    - host: {{ .Values.domain3 | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "nginx-hello.fullname" . }}-service
                port:
                  number: {{ .Values.service.port }}
    {{- end }}
    {{- end }}
{{- end }}