name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Build image
        run: docker build -t nginx-hello:test .
      
      - name: Test runtime
        run: |
          docker run -d --name test -p 8080:80 nginx-hello:test
          sleep 5
          curl -f http://localhost:8080/ | grep "Hello World"
          curl -f http://localhost:8080/health | grep "OK"
          docker stop test

      - name: Test Kubernetes
        uses: helm/kind-action@v1.10.0
        with:
          cluster_name: test

      - name: Deploy to Kind
        run: |
          kind load docker-image nginx-hello:test --name test
          kubectl apply -f k8s/configmap.yaml
          sed 's/nginx_hello-nginx:latest/nginx-hello:test/g' k8s/k8s-deployment.yaml | kubectl apply -f -
          kubectl wait --for=condition=ready pod -l app=nginx-hello --timeout=120s

  security:
    runs-on: ubuntu-latest
    needs: test
    if: github.event_name == 'push'
    steps:
      - uses: actions/checkout@v4
      
      - name: Build image for security scan
        run: docker build -t nginx-hello:test .
      
      - name: Security scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: nginx-hello:test
          format: 'table'