name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Build image
        run: docker build -t nginx-hello:test .
      
      - name: Test runtime
        run: |
          docker run -d --name test -p 8080:80 nginx-hello:test
          # Wait for the container to be ready
          for i in $(seq 1 10); do
            sleep 2
            curl -f http://localhost:8080/health && break
            echo "Waiting for container to be ready..."
          done
          curl -f http://localhost:8080/ | grep "Hello World"
          curl -f http://localhost:8080/health | grep "OK"
          docker stop test

      - name: Test Kubernetes
        uses: helm/kind-action@v1.10.0
        with:
          cluster_name: test

      - name: Deploy to Kind
        run: |
          kind load docker-image nginx-hello:test --name test
          kubectl apply -f k8s/configmap.yaml
          sed 's/nginx_hello-nginx:latest/nginx-hello:test/g' k8s/k8s-deployment.yaml | kubectl apply -f -
          
      - name: Wait for deployment
        run: |
          kubectl get pods -l app=nginx-hello
          kubectl describe deployment nginx-hello
          sleep 10
          kubectl describe pods -l app=nginx-hello
          kubectl rollout status deployment/nginx-hello --timeout=180s
          kubectl wait --for=condition=ready pod -l app=nginx-hello --timeout=60s

      - name: Debug deployment
        if: always()
        run: |
          echo "--- Pods status ---"
          kubectl get pods -l app=nginx-hello -o wide
          echo "--- Describe pods ---"
          for pod in $(kubectl get pods -l app=nginx-hello -o jsonpath='{.items[*].metadata.name}'); do
            echo "--- Describing pod: $pod ---"
            kubectl describe pod $pod
            echo "--- Logs for pod: $pod ---"
            kubectl logs $pod --all-containers=true
          done
          
      - name: Test endpoints
        run: |
          POD_NAME=$(kubectl get pods -l app=nginx-hello -o jsonpath='{.items[0].metadata.name}')
          kubectl exec $POD_NAME -- curl -s http://localhost/ | grep -q "Hello World" && echo "✅ Main page OK"
          kubectl exec $POD_NAME -- curl -s http://localhost/health | grep -q "OK" && echo "✅ Health check OK"

  security:
    runs-on: ubuntu-latest
    needs: test
    if: github.event_name == 'push'
    steps:
      - uses: actions/checkout@v4
      
      - name: Build image for security scan
        run: docker build -t nginx-hello:test .
      
      - name: Security scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: nginx-hello:test
          format: 'table'